### ISSUE TITLE
datavalid

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#324]
hey @pckhoi 

I'm receiving the following error message re `datavalid`  when I attempt to access a `.py` script in the clean directory:

`ImportError: cannot import name 'load_config' from 'datavalid' (/usr/local/lib/python3.10/dist-packages/datavalid/__init__.py)`

Please advise

**Comment by pckhoi** [comment]
Hey Ayyub, I don't think any library support python 3.10 yet. Can you downgrade to python 3.9 and try again?

**Comment by ayyubibrahimi** [comment]
Disregard. 

For some reason, packages won't install properly if I run:  `pip install -r requirements.txt`

But, installation seems to work if I install each package separately, i.e., `python -m pip install datavalid==0.3.6`

This works with python 3.10. If I run into further issues, I' will downgrade to 3.9.

**Comment by pckhoi** [comment]
Well that means `pip` and `python` belongs to different installations. You can check by running `which pip` and `which python` under WSL. It will probably show those files living in 2 different folders. Ideally, they should live in one folder only. You should probably look at using virtualenvwrapper under WSL.

**Comment by ayyubibrahimi** [comment]
Thanks. Resolved.
